version: '2'
services:
  dev:
    image: "dev:python3"
    build:
      context: "./dev"
      dockerfile: ./Dockerfile
      args:
        # Update 'VARIANT' to pick a Python version: 3, 3.10, 3.11, 3.12, 3.13
        # Available image variants: https://github.com/microsoft/vscode-dev-containers/blob/main/containers/python-3/README.md
        VARIANT: "3"
    volumes:
      - ../:/opt/dev/code:cached
      - ./dev/.vscode:/opt/dev/.vscode:cached
    tty: true
    command: bash
